inflectiontest/urls.py
from django.contrib import admin
from django.urls import path,re_path,include
from django.conf import settings
from django.conf.urls.static import static
from customauth.views import *
from core.views import *
from machina import urls as machina_urls

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path(r'^accounts/', include('allauth.urls')),
    re_path(r'^$', home, name="home"),

    re_path(r'^ckeditor/', include('ckeditor_uploader.urls')),

    re_path(r'^accounts/profile/$', user_profile, name='account_profile'),

    re_path(r'^accounts/verify/$', teacher_student_verification, name='teacher_student_verification'),

    re_path(r'^accounts/profile/verify/$', verify_teacher, name='verify_teacher'),

    re_path(r'^accounts/profile/add-course/$', student_add_course, name='student-add-course'),

    path('questions/<int:id>/', single_question, name="single_question"),

 	 path('accounts/profile/<str:course_uuid>/', course_detail),
     path('accounts/profile/student/<str:course_uuid>/', course_detail_student),


     path('accounts/profile/<str:course_uuid>/subscribe/', teacher_subscribe_course),





   

     path('forum/', include(machina_urls)),
     
    
     re_path(r'^vocabulary/$', vocabulary, name='vocabulary'),
     path('vocabulary/<slug:slug>/',lesson_vocabulary, name='lesson_vocabulary'),
     re_path(r'^courses/$', teacher_student_modules, name='teacher_student_modules'),

     path('course/<str:slug>/', module_topic_list, name="module_topic_list"),
     path('course/<slug:course_slug>/<slug:topic_slug>/', module_lesson_list, name="module_lesson_list"),
     path('course/<slug:course_slug>/<slug:topic_slug>/pre-assessment/<int:id>', module_pre_assessment, name="module_pre_assessment"),
     path('course/<slug:course_slug>/<slug:topic_slug>/post-assessment/<int:id>', module_post_assessment, name="module_post_assessment"),

     path('course/<slug:course_slug>/<slug:topic_slug>/<slug:lesson_slug>/<slug:lessoncontent_slug>', module_lesson, name="module_lesson"),
     

     re_path(r'^students/products/$',  products_list, name='products_list'),
     path('students/products/<slug:slug>/',product_module_list, name='product_module_list'),
     path('students/products/<slug:product_slug>/<slug:course_slug>/classes',product_module_class_list, name='product_module_class_list'),
     path('<slug:slug>/students',class_students_list, name='class_students_list'),


     path('statistics/<slug:slug>',dashboard_single_student_stats, name='dashboard_single_student_stats'),
     path('statistics/<slug:user_slug>/<slug:course_slug>',dashboard_single_student_topic_list, name='dashboard_single_student_topic_list'),
  
     path('statistics/<slug:user_slug>/<slug:course_slug>/<slug:topic_slug>',dashboard_single_student_lessons_list, name='dashboard_single_student_lessons_list'),


    #DASHBOARD URLS
    path('dashboard/', dashboard,name='dashboard'),
    path('dashboard/<str:slug>/', dashboard_topic_list, name="dashboard_topic_list"),
    path('dashboard/<slug:course_slug>/<slug:topic_slug>/', dashboard_lesson_list, name="dashboard_lesson_list"),

     re_path(r'^api-auth/', include('rest_framework.urls')),
     re_path(r'^api/core/', include("core.api.urls")),


     re_path(r'^ajax/get-similar-words/$', ajax_similar_word_rankings, name='get-similar-words'),
     re_path(r'^ajax/get-ner-type/$', ajax_ner_model, name='get-ner-type'), 
     re_path(r'^ajax/get-pos-type/$', ajax_pos_model, name='get-pos-type'), 

     re_path(r'^ajax/get-sim-to-words/$', ajax_sim_to_words, name='get-sim-to-words'),

     re_path(r'^ajax/word-addition/$', ajax_word_addition, name='word-addition'), 

     re_path(r'^ajax/word-to-plot/$', ajax_word_to_plot, name='word-to-plot'), 
   

   
   
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.db import models
from django.conf import settings
# Create your models here.
import uuid
from django.db.models import Q

from django.contrib.auth import get_user_model


from django.contrib.auth.models import AbstractUser,BaseUserManager

from django.db.models.signals import pre_save
from .utils import unique_slug_generator
from ckeditor.fields import RichTextField
from ckeditor_uploader.fields import RichTextUploadingField
User = settings.AUTH_USER_MODEL



Question_Types_Choices = (
    ('multiple_choice', ('multiple_choice')),
    ('text_input', ('text_input'))
)





class Products(models.Model):
	name = models.CharField(max_length=1000)
	slug = models.SlugField(blank=True,null=True,unique=True)

	def __str__(self):
		return self.name

	def get_slug_url(self):
		return f"/students/products/{self.slug}"

class QuestionManager(models.Manager):
	def get_unanswered(self, user,topic):
		q1 = Q(userpreassessmentanswer__user = user)
		# q2 = Q(userpreassessmentanswer__topic = topic)
		q3 = Q(assessment_type = 'post_assessment')
		qs = self.exclude(q1 | q3)
		print("The [pre qs is",qs)
		return qs

	def get_post_unanswered(self, user,topic_slug):
		q1 = Q(userpostassessmentanswer__user = user)
		# q2 = Q(userpostassessmentanswer__topic__slug = topic_slug)
		q3 = Q(assessment_type = 'pre_assessment')
		qs = self.exclude(q1 | q3)
		return qs






class School(models.Model):
	name = models.CharField(max_length = 500)
	address = models.CharField(max_length = 500)
	contact = models.CharField(max_length = 500)
	district = models.CharField(max_length = 500)
	school_uuid =  models.UUIDField(default=uuid.uuid4, editable=False,unique=True)
	timestamp = models.DateTimeField(auto_now_add=True, auto_now=False)
	updated = models.DateTimeField(auto_now=True)


	def __str__(self):
		return self.name



Assessment_Type_Choices = (
    ('pre_assessment', ('pre_assessment')),
    ('post_assessment', ('post_assessment'))
)



class Question(models.Model):
	text = models.TextField()
	active = models.BooleanField(default=True)
	question_type = models.CharField(max_length = 250, choices = Question_Types_Choices)
	correct_answer = models.TextField(blank=True,null=True)
	attempts_allowed = models.IntegerField(default = 2)
	pre_assessment = models.BooleanField(default=False)
	timestamp = models.DateTimeField(auto_now_add=True, auto_now=False)
	updated = models.DateTimeField(auto_now=True)


	objects = QuestionManager()


	def __str__(self):
		return self.text


class PrePostQuestion(models.Model):
	text = RichTextUploadingField()
	active = models.BooleanField(default=True)
	topic  = models.ForeignKey('Topic',on_delete=models.CASCADE)
	question_type = models.CharField(max_length = 250, choices = Question_Types_Choices)
	correct_answer = models.TextField(blank=True,null=True)
	attempts_allowed = models.IntegerField(default = 2)
	assessment_type = models.CharField(max_length = 250, choices = Assessment_Type_Choices)
	timestamp = models.DateTimeField(auto_now_add=True, auto_now=False)
	updated = models.DateTimeField(auto_now=True)


	objects = QuestionManager()


	def __str__(self):
		return self.text



class Answer(models.Model):
	question = models.ForeignKey(Question,on_delete=models.CASCADE)
	text = models.TextField(blank=True,null=True)
	active = models.BooleanField(default=True)
	timestamp = models.DateTimeField(auto_now_add=True , auto_now=False)
	updated = models.DateTimeField(auto_now=True)

	def __str__(self):
		return self.text


class FreeTextAnswer(models.Model):
	question = models.ForeignKey(Question,on_delete=models.CASCADE)
	text = models.TextField(blank=True, null=True)
	active = models.BooleanField(default=True)
	timestamp = models.DateTimeField(auto_now_add=True , auto_now=False)

	def __unicode__(self):
		return self.text[:10]



class UserAnswer(models.Model):
	user = models.ForeignKey(User,on_delete=models.CASCADE)
	question = models.ForeignKey(Question,on_delete=models.CASCADE)  
	my_answer = models.ForeignKey(Answer,on_delete=models.CASCADE,blank=True,null=True)
	my_points = models.IntegerField(default=-1)
	attempts_used = models.IntegerField(default=0)
	answer_given = models.BooleanField(default=False)
	correct_answer = models.BooleanField(default=False)
	timestamp = models.DateTimeField(auto_now_add=True, auto_now=False)


	def __unicode__(self):
		return self.my_answer.text[:10]



class PrePostAnswer(models.Model):
	question = models.ForeignKey(PrePostQuestion,on_delete=models.CASCADE)
	text = models.TextField(blank=True,null=True)
	active = models.BooleanField(default=True)
	timestamp = models.DateTimeField(auto_now_add=True , auto_now=False)
	updated = models.DateTimeField(auto_now=True)

	def __str__(self):
		return self.text


class UserPreAssessmentAnswer(models.Model):
	user = models.ForeignKey(User,on_delete=models.CASCADE)
	topic = models.ForeignKey('Topic',on_delete=models.CASCADE,blank=True,null=True)
	question = models.ForeignKey(PrePostQuestion,on_delete=models.CASCADE)  
	my_answer = models.ForeignKey(PrePostAnswer,on_delete=models.CASCADE,blank=True,null=True)
	my_points = models.IntegerField(default=-1)
	attempts_used = models.IntegerField(default=0)
	answer_given = models.BooleanField(default=False)
	correct_answer = models.BooleanField(default=False)
	timestamp = models.DateTimeField(auto_now_add=True, auto_now=False)


	def __unicode__(self):
		return self.my_answer.text[:10]


class UserPostAssessmentAnswer(models.Model):
	user = models.ForeignKey(User,on_delete=models.CASCADE)
	topic = models.ForeignKey('Topic',on_delete=models.CASCADE,blank=True,null=True)
	question = models.ForeignKey(PrePostQuestion,on_delete=models.CASCADE)  
	my_answer = models.ForeignKey(PrePostAnswer,on_delete=models.CASCADE,blank=True,null=True)
	my_points = models.IntegerField(default=-1)
	attempts_used = models.IntegerField(default=0)
	answer_given = models.BooleanField(default=False)
	correct_answer = models.BooleanField(default=False)
	timestamp = models.DateTimeField(auto_now_add=True, auto_now=False)


	def __unicode__(self):
		return self.my_answer.text[:10]






class UserTextAnswer(models.Model):
	user = models.ForeignKey(User,on_delete=models.CASCADE)
	question = models.ForeignKey(Question,on_delete=models.CASCADE)  
	my_answer = models.ForeignKey(FreeTextAnswer,on_delete=models.CASCADE)
	my_points = models.IntegerField(default=-1)
	answer_given = models.BooleanField(default=False)
	timestamp = models.DateTimeField(auto_now_add=True, auto_now=False)

	def __unicode__(self):
		return self.my_answer.text[:10]



def image_upload_to(instance, filename):
	title = instance.name

	return "course-images/%s/%s" %(title, filename)


class Class(models.Model):
	name = models.CharField(max_length=255)
	slug = models.SlugField()
	class_uuid = models.UUIDField(default=uuid.uuid4, editable=False,unique=True)

	def __str__(self):
		return self.name

class TeacherClass(models.Model):
	course = models.ForeignKey('Course',on_delete=models.CASCADE)
	name = models.CharField(max_length=255)
	slug = models.SlugField()
	teacher = models.ForeignKey('TeacherProfile',on_delete=models.CASCADE,blank=True,null=True)
	class_uuid = models.UUIDField(default=uuid.uuid4, editable=False,unique=True)

	def __str__(self):
		return self.name

	def get_class_student_list_url(self):
		return f"/{self.slug}/students"






class Course(models.Model):
	product = models.ForeignKey('Products',on_delete=models.CASCADE)
	name = models.CharField(max_length = 255)
	slug = models.SlugField(blank=True,null=True,unique=True)
	image   = models.ImageField(upload_to=image_upload_to, blank=True, null=True)
	course_uuid = models.UUIDField(default=uuid.uuid4, editable=False,unique=True)
	timestamp = models.DateTimeField(auto_now_add=True , auto_now=False)
	updated = models.DateTimeField(auto_now=True)



	def __str__(self):
		return self.name

	def get_slug_url(self):

		return f"/course/{self.slug}"

	def get_dashboard_topic_url(self):
		return f"/dashboard/{self.slug}"


	def get_teacher_class_list_url(self):

		return f"/students/products/{self.slug}/classes"


	def get_absolute_url(self):

		return f"/accounts/profile/{self.course_uuid}"

	def get_absolute_url_student(self):

		return f"/accounts/profile/student/{self.course_uuid}"

	def get_subscribe_url(self):
		return f"{self.get_absolute_url()}/subscribe"

	def get_unsubscribe_url(self):
		return f"{self.get_absolute_url()}/unsubscribe"

	def get_question_absolute_url(self):
		return f"/questions/{self.id}"

	def get_student_product_class_url(self):
		return f"/students/products/{self.product.slug}/{self.slug}/classes"



class Topic(models.Model):
	course = models.ForeignKey('Course',on_delete=models.CASCADE)
	name = models.CharField(max_length=255)
	description = models.CharField(max_length=255)
	slug = models.SlugField(blank=True,null=True)


	def __str__(self):
		return self.name

	def get_slug_url(self):

		return f"/course/{self.course.slug}/{self.slug}"

	def get_pre_assessment_url(self):

		return f"/course/{self.course.slug}/{self.slug}/pre-assessment/{self.prepostquestion_set.all().filter(assessment_type = 'pre_assessment')[0].id}"

	def get_post_assessment_url(self):
		post_assessment_question = self.prepostquestion_set.all().filter(assessment_type = 'post_assessment')
		if post_assessment_question.count() > 0:

			return f"/course/{self.course.slug}/{self.slug}/post-assessment/{self.prepostquestion_set.all().filter(assessment_type = 'post_assessment')[0].id}"
		else:
			return f"/course/{self.course.slug}/{self.slug}"


	def get_dashboard_slug_url(self):

		return f"/dashboard/{self.course.slug}/{self.slug}"




class Lesson(models.Model):
	topic = models.ForeignKey('Topic',on_delete=models.CASCADE)
	name = models.CharField(max_length=255)
	slug = models.SlugField()

	class Meta:
		ordering = ['id']

	def __str__(self):
		return self.name

	def get_absolute_url(self):

core/forms.py
from django import forms
from django.forms import fields, models, formsets, widgets,ModelForm ,modelformset_factory

from .models import *
from django.contrib.auth import authenticate, login, get_user_model
from django.contrib.auth.forms import ReadOnlyPasswordHashField
User = get_user_model()

class UserAdminChangeForm(forms.ModelForm):
    """A form for updating users. Includes all the fields on
    the user, but replaces the password field with admin's
    password hash display field.
    """
    password = ReadOnlyPasswordHashField()

    class Meta:
        model = User
        fields = ('first_name', 'email', 'password', 'is_active')

    def clean_password(self):
        # Regardless of what the user provides, return the initial value.
        # This is done here, rather than on the field, because the
        # field does not have access to the initial value
        return self.initial["password"]


class UserAdminCreationForm(forms.ModelForm):
    """A form for creating new users. Includes all the required
    fields, plus a repeated password."""
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Password confirmation', widget=forms.PasswordInput)
    

    class Meta:
        model = User
        fields = ('first_name','last_name', 'email',) #'full_name',)

    def clean_password2(self):
        # Check that the two password entries match
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Passwords don't match")
        return password2

    def save(self, commit=True):
        # Save the provided password in hashed format
        user = super(UserAdminCreationForm, self).save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user


class UserResponseForm(forms.Form):
	question_id = forms.IntegerField()
	answer_id = forms.IntegerField()


class UserTextFreeForm(forms.Form):
	question_id = forms.IntegerField()
	my_answer = forms.CharField(widget=forms.Textarea)


class TestFileForm(ModelForm):
	class Meta:
		model = TestFile
		exclude = ['user_file_text','file_name']
		



#---------


class SignupForm(forms.ModelForm):
	   # teacher_student = forms.CharField(max_length=10,label='phone_number')
	PERSON_TYPE_CHOICES = (
	    ('Teacher', ('Teacher')),
	    ('Student', ('Student ')),
	)
	teacher_student = forms.ChoiceField(choices=PERSON_TYPE_CHOICES, widget=forms.RadioSelect())
	class Meta:
		model = User
		fields = ['email','teacher_student']


 

	def signup(self, request, user):

		user.teacher_student = self.cleaned_data['teacher_student']
		user.save()




class TeacherVerificationForm(forms.Form):

	school_name = forms.CharField(label='School Name', max_length=500)
	school_uuid = forms.CharField(label='School ID',   max_length=500)


class StudentAddCourseForm(forms.Form):
	teacher_email =  forms.EmailField(label='Teacher Email')
	course_uuid = forms.CharField(label = 'Course ID')



class NLPModelForm(forms.Form):
    model_name =  forms.CharField(label='Enter the model name to be used')
    word = forms.CharField(label = 'Enter a word')

templates/class_students_list.html
{% extends 'new_base.html' %}

{% load static %}

{% block navbar_items %}

          <ul class="navbar-nav ml-auto">
            <li class="nav-item ">
              <a class="nav-link" href="{% url 'teacher_student_modules' %}">
                <img src="{% static 'img/icons/list.svg' %}" alt="icon">
                Modules list
              </a>
            </li>
            <li class="nav-item ">
              <a class="nav-link" href="{% url 'vocabulary' %}">
                <img src="{% static 'img/icons/vocabulary.svg' %}" alt="icon">
                Vocabulary
              </a>
            </li>
            <li class="nav-item ">
              <a class="nav-link" href="{% url 'dashboard' %}">
                <img src="{% static 'img/icons/dashboard.svg' %}" alt="icon">
                Dashboard
              </a>
            </li>
            {% if request.user.teacher_student == "Teacher" %}
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'products_list' %}">
                <img src="{% static 'img/icons/people.svg' %}" alt="icon">
                Students
              </a>
            </li>
            {% endif %}
            <li class="nav-item">
              <div class="btn-group">
                <button type="button" class="btn dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  <img src="{% static 'img/icons/person.svg' %}" alt="icon">
                  My profile
                </button>
                <div class="dropdown-menu dropdown-menu-right">
                  <div class="profile-info">
                    <div class="name">
                      <span>
                        {% if request.user.first_name and request.user.last_name %}

                        {{ request.user.first_name }} {{ request.user.last_name }}

                        {% else %}

                        You have not entered your details

                        {% endif %}


                      </span>
                      <a href="{% url 'account_profile' %}"  >
                        <img src="{% static 'img/icons/pen.svg' %}" alt="icon">
                      </a>
                    </div>
                    <div class="email">
                      <img src="{% static 'img/icons/envelope.svg' %}" alt="icon">
                      {{request.user.email}}
                    </div>
                    <div class="position">
                      <img src="{% static 'img/icons/magister.svg' %}" alt="icon">
                      {{request.user.teacherprofile_set.all.0.school.name }}
                    </div>
                  </div>
                  <a class="dropdown-links change-password" href="{% url 'account_change_password' %}">
                    <img src="{% static 'img/icons/lock.svg' %}" alt="icon">
                    Change password
                  </a>
                  <a class="dropdown-links logout" href="{% url 'account_logout' %}">
                    <i class="fas fa-sign-out-alt"></i>
                    Logout
                  </a>
                </div>
              </div>
            </li>
          </ul>

{% endblock %}

{% block content %}


      <div class="row">

        <div class="sidebar">
          <div id="sidebar-container" class="sidebar-expanded d-none d-md-block">
            <div class="sidebar-title-wrapper d-flex justify-content-between">
              <div class="sidebar-separator-title sidebar-title d-flex align-items-center menu-collapsed">
                <small>Your course</small>
              </div>
              <a href="#" data-toggle="sidebar-colapse" class="d-flex align-items-center">
                <div class="icon-collapse-wrapper d-flex w-100 justify-content-start align-items-center">
                  <img src="{% static 'img/icons/menu.svg' %}" alt="icon">
                </div>
              </a>
            </div>

        <ul class="nav nav-list">
              {% if request.user.teacher_student == "Teacher" %}
              {% for product in products %}
              <li>
                <a href="#" class="accordion-heading" data-toggle="collapse" data-target="#submenu-{{product.slug}}">
                  <div class="main-menu-item menu-item-wrapper d-flex w-100 justify-content-start align-items-center">
                    <i id="collapse-folder-icon-main" class="fas fa-folder active"></i>
                    <span class="menu-collapsed menu-item-title">{{product.name}}</span>
                  </div>
                  <div class="line"></div>
                </a>

                <ul class="nav nav-list collapse submenu submenu-{{product.slug}}" id="submenu-{{product.slug}}">
                  <li>
                    {% for teacher_course in product.course_set.all %}
                    {% with forloop.counter as second_counter %}
                    <a href="#" class="accordion-heading" data-toggle="collapse" data-target="#submenu{{teacher_course.slug}}">
                      <div class="sub-menu-item menu-item-wrapper d-flex w-100 justify-content-start align-items-center">
                        <i id="collapse-folder-icon-sub" class="fas fa-folder"></i>
                        <span class="menu-collapsed menu-item-title">{{ teacher_course.name }}</span>
                      </div>
                      <div class="line"></div>

                      {% for teacher_class in teacher_profile.teacherclass_set.all %}
                      {% if teacher_class.course.name == teacher_course.name %}
                      <ul class="nav nav-list collapse submenu{{teacher_course.slug}}" id="submenu{{teacher_course.slug}}">
                        <li>
                          
                          <a href="{{ teacher_course.get_student_product_class_url}}" class="">
                            <div class="menu-item-wrapper current d-flex w-100 justify-content-start align-items-center">
                              <img src="{% static 'img/icons/dot.svg' %}" alt="icon">
                              <span class="menu-collapsed menu-item-title">{{teacher_class.name}}</span>
                            </div>
                            <div class="line"></div>
                          </a>
                        </li>
                      </ul>
                      {% endif %}
                      {% endfor %}
                    </a>
                    {% endwith %}
                    {% endfor %}
                  </li>
                </ul>


              </li>
              {% endfor %}

              {% elif request.user.teacher_student == "Student" %}
            {% for student_course in student_profile.course.all %}
              <li>
                <a href="#" class="accordion-heading" data-toggle="collapse" data-target="#submenu{{student_course.slug}}">
                  <div class="main-menu-item menu-item-wrapper d-flex w-100 justify-content-start align-items-center">
                    <i id="collapse-folder-icon-main" class="fas fa-folder active"></i>
                    <span class="menu-collapsed menu-item-title">{{student_course.name}}</span>
                  </div>
                  <div class="line"></div>
                </a>

                <ul class="nav nav-list collapse submenu submenu{{student_course.slug}}" id="submenu{{student_course.slug}}">
                  <li>
                    {% for topic in student_course.topic_set.all %}
                    {% with forloop.counter as second_counter %}
                    <a href="#" class="accordion-heading" data-toggle="collapse" data-target="#submenu{{topic.slug}}">
                      <div class="sub-menu-item menu-item-wrapper d-flex w-100 justify-content-start align-items-center">
                        <i id="collapse-folder-icon-sub" class="fas fa-folder"></i>
                        <span class="menu-collapsed menu-item-title">{{ topic.name }}</span>
                      </div>
                      <div class="line"></div>

                      {% for lesson in topic.lesson_set.all %}
                      <ul class="nav nav-list collapse submenu{{topic.slug}}" id="submenu{{topic.slug}}">
                        <li>
                           <a href="{{ lesson.lessoncontent_set.all.0.get_absolute_url }}" class="">
                            <div class="menu-item-wrapper current d-flex w-100 justify-content-start align-items-center">
                              <img src="{% static 'img/icons/dot.svg' %}" alt="icon">
                              <span class="menu-collapsed menu-item-title">{{lesson.name}}</span>
                            </div>
                            <div class="line"></div>
                          </a>
                        </li>
                      </ul>
                      {% endfor %}
                    </a>
                    {% endwith %}
                    {% endfor %}
                  </li>
                </ul>


              </li>
              {% endfor %}
               {% endif %}
           <!--    <li>
                <a href="#" class="">
                  <div class="menu-item-wrapper d-flex w-100 justify-content-start align-items-center">
                    <i class="fas fa-folder"></i>
                    <span class="menu-collapsed menu-item-title">System analysis</span>
                  </div>
                  <div class="line"></div>
                </a>
              </li> -->
            </ul>

            <ul class="list-group">

              <!--<a href="#submenu1" data-toggle="collapse" aria-expanded="false" class="bg-dark list-group-item list-group-item-action flex-column align-items-start">-->
              <!--<div class="d-flex w-100 justify-content-start align-items-center">-->
              <!--<i class="fas fa-folder"></i>-->
              <!--<span class="menu-collapsed">Data fundamentals</span>-->
              <!--</div>-->
              <!--</a>-->

              <!-- Submenu content -->
              <!--<div id='submenu1' class="collapse sidebar-submenu">-->
              <!--<a href="#" class="list-group-item list-group-item-action bg-dark text-white">-->
              <!--<span class="menu-collapsed">Charts</span>-->
              <!--</a>-->
              <!--<a href="#" class="list-group-item list-group-item-action bg-dark text-white">-->
              <!--<span class="menu-collapsed">Reports</span>-->
              <!--</a>-->
              <!--<a href="#" class="list-group-item list-group-item-action bg-dark text-white">-->
              <!--<span class="menu-collapsed">Tables</span>-->
              <!--</a>-->
              <!--</div>-->
            </ul><!-- List Group END-->
          </div><!-- sidebar-container END -->
        </div>
        <div class="content">
          <div class="content-title">
            <h1>{{teacher_class}} </h1>
            <a href="#" class="title-search">
              <i class="fas fa-search"></i>
            </a>

            
          </div>

          <div class="data-list">

      {% if  teacher_class.studentprofile_set.all.count == 0  %} 

      <h3>You do not have any students in this class yet.</h3>


      {% else %} 
          	{% for student in teacher_class.studentprofile_set.all %}
            <div class="data-element">
              <div class="title">
                <h3 class="name">{{ student.user.first_name }} {{ student.user.last_name }} </h3>
                
              </div>
              <div class="body">
                <div class="left-part">
                  <div class="students">
                    <img src="{% static 'img/icons/envelope.svg' %}" alt="icon">
                    {{student.user.email}}
                  </div>
                </div>

                <div class="right-part">
                  <div class="links">
                    <a href="{{ student.get_student_stats_url }}" class="first-link">
                      <img class="graph" src="{% static 'img/icons/graph.svg' %}" alt="icon">
                      View statistics
                    </a>
                  </div>
                </div>
              </div>
            </div>


            {% endfor %}
 {% endif %}
          </div>
        </div>
      </div>

{% endblock %}

templates/course_detail.html
{% extends 'base.html' %}


{% block content %}


<h3>Welcome to {{ course.name }}</h3>

<h4>Note: Hand over the following details to your students to let them register to your course. Do not share the details with anyone else other than your students</h4>

<p>Email: {{ instance.teacher.user.email }} </p>
<p>Course ID: {{ instance.course_uuid }}</p>




<h3>This course contains the following topics:</h3>

<ul>
	{% for topic in course.topic_set.all %}

	<li>{{ topic.name }}</li>
	{% endfor %}
</ul>


{% endblock %}